/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativecall_NativeHello */

#ifndef _Included_nativecall_NativeHello
#define _Included_nativecall_NativeHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativecall_NativeHello
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativecall_NativeHello_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
